routes/web.php
<?php
//header('Access-Control-Allow-Origin:  *');
//Route::get('/', 'TestimonialsController@home')->name('landing-page');
Route::get('/', function () {
    return view('welcome');
});


Route::get('/usuarios/activacion/{token}', 'Auth\RegisterController@activar');
//Route::get('/', 'loginController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::middleware(['auth'])->group(function () {

    Route::get('/pbi', 'PbisController@show')->name('pbi.show');
    Route::patch('/pbiEstado/{tarea}', 'PbisController@cambiarEst');
    Route::delete('/tarea/{tarea}', 'PbisController@destroyT');
    //Route::post('/tareas/create', 'TareasControlador@create')->name('tareas.create');
    Route::get('pbis/{pbi}/tareas/create', 'TareasControlador@create')->name('tareas.create');
    Route::post('/tareas/store', 'TareasControlador@store')->name('tareas.store');
    Route::get('/tareas/edit/{tarea}', 'TareasControlador@edit')->name('tareas.edit');
    Route::post('/tareas/update', 'TareasControlador@update')->name('tareas.update');

    Route::post('/tareas/subir', 'TareasControlador@subir')->name('tareas.subir');
    Route::get('/tareas/{tarea}/eliminar', 'TareasControlador@eliminar')->name('tarea.eliminar') ;
    Route::post('/tareas/delete', 'TareasControlador@borrar')->name('tarea.borrar');
    Route::get('/tareas/recuperar/{id}', 'TareasControlador@recuperar')->name('tarea.recuperar');
    Route::get('/tareas/{id}/historial', 'TareasControlador@historial')->name('tarea.historial');
    //Route::post('/tareas/delete/{id}', 'TareasControlador@borrar')->name('tarea.borrar');

    Route::get('/tareas/eliminararchivo/{id}', 'TareasControlador@deleteFile')->name('tarea.deletefile') ;

    
    Route::get('/proyecto/{project}/miembros', 'EquipoControlador@show')->name('miembros.show');
    Route::get('/miembros/eliminar/{projectuser}', 'EquipoControlador@destroy')->name('miembros.eliminar');
    Route::post('/miembros/anadir', 'EquipoControlador@anadir')->name('equipo.anadir');


    Route::get('/pbis/{pbi}/comentarios', 'ComentarioControlador@show')->name('coment.show');
    Route::post('/comentarios/crear', 'ComentarioControlador@store')->name('coment.store');
    Route::get('/comentario/{comentario}/eliminar', 'ComentarioControlador@destroy')->name('coment.elim');


    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::get('/projects/{project}/papelera/historias','ProjectsController@papelera_historias');
    Route::get('/projects/{project}/papelera/tareas','ProjectsController@papelera_tareas');
    
    Route::resource('companias', 'CompaniesController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('roles', 'RolesController');
    //Route::resource('tareas', 'TareasControlador');
    Route::resource('users', 'UsersController');
    //Route::resource('comments', 'CommentsController');
    Route::resource('pbis', 'PbisController');
    Route::resource('sprints', 'SprintsControlador');


    Route::get('/usuarios/{user}/editar', 'UsersController@edit')->name('usuarios.edit');
    Route::post('/usuarios/actualizar', 'UsersController@update')->name('usuarios.update');
    Route::get('/usuarios/{user}/eliminar', 'UsersController@destroy')->name('usuarios.delete');
    
    Route::get('/usuarios/{user}/activacion', 'UsersController@camEstado')->name('usuarios.cambiar');


    Route::get('pbis/edit/{id}', 'PbisController@edit')->name('pbis.edit');
    Route::get('pbis/update', 'PbisController@update')->name('pbis.update');
    Route::get('/pbis/delete/{id}', 'PbisController@eliminar')->name('pbis.eliminar');
    Route::post('/pbis/delete', 'PbisController@destroy')->name('pbis.delete');
    Route::get('/pbis/recuperar/{id}', 'PbisController@recuperar')->name('pbis.recuperar');
    Route::get('/pbis/{id}/historial', 'PbisController@historial')->name('pbis.historial');
    

    Route::get('sprints', 'SprintsControlador@store');
    Route::post('/sprints/create', 'SprintsControlador@create');
    Route::get('/sprints/delete/{id}', 'SprintsControlador@destroy')->name('sprints.delete');
    Route::get('sprints/edit/{id}', 'SprintsControlador@edit')->name('sprints.edit');
    Route::post('/sprints/update', 'SprintsControlador@update')->name('sprints.update');
    //Route::get('sprints/create', 'ProjectsController@createSprint');
    //Route::get('pbis/create', 'PbisController@store')->name('pbis.store');

    //administrador
    Route::get('/admin/proyectos', 'ProjectsController@todos')->name('proyecto.todos');
    Route::get('/admin/{project}/eliminar', 'ProjectsController@destroy_admin')->name('proyecto.delete');
    //reportes
    Route::get('projects/{project}/reporte/sprints', 'ReportesControlador@rep_sprints');
    Route::get('projects/{project}/reportes', 'ReportesControlador@rep_pro_bac');
    Route::get('projects/{project}/reporte/tareas', 'ReportesControlador@rep_tar');
    Route::get('projects/{project}/reporte/tareas_estado', 'ReportesControlador@rep_tar_est');
    Route::get('projects/{project}/reporte/equipo', 'ReportesControlador@rep_usuarios');

    
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'name',
        'description',
        //'company_id',
        'user_id',
        'days',

    ];


    public function users(){
		  return $this->belongsToMany('App\User');
    }

    public function sprints()
    {
    	return $this->hasMany('App\Sprint');
    }

   

}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
use App\ProjectUser;
use App\User;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
  /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function todos()
     {
        if( Auth::check() ){
        $proyectos = Project::all();
        $num_proyects =count($proyectos);
        return view('projects.todos', compact('proyectos','num_proyects'));  
        }
     }

     public function index()
     {
        if( Auth::check() ){
        $projects = Project::where('user_id', Auth::user()->id)->get();

        $proyectosInv = \DB::table('project_user')
        ->join('projects', 'project_user.project_id', '=', 'projects.id')
        ->where('project_user.user_id', Auth::user()->id)
        ->where('project_user.invitado', 1)
        ->get();

        return view('projects.index', compact('projects', 'proyectosInv'));  
        }
         
     }

     public function create(  )
     {
         
         return view('projects.create');
     }
 
     /**
      * Store a newly created resource in storage.
      *
      * @param  \Illuminate\Http\Request  $request
      * @return \Illuminate\Http\Response
      */
     public function store(Request $request)
     {
        $this->validate( $request, [
            'nombre' => 'required | unique:projects,name,user_id'
        ]) ;

        if(Auth::check()){
            $pro_creado = Project::create([
                'name' => $request->input('nombre'),
                'description' => $request->input('description'),
                //'company_id' => $request->input('company_id'),
                'user_id' => Auth::user()->id
            ]);

            if($pro_creado){
                return redirect()->route('projects.show', ['project'=> $pro_creado->id])
                ->with('success' , 'El proyecto fue creado exitosamente');
            }
        }
        return back()->withInput()->with('errors', 'No se pudo crear el proyecto');
 
     }

     /**
      * Display the specified resource.
      *
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function show(Project $project)
     {

        $project = Project::find($project->id);
        
        $pbis = \DB::table('sprints')
        ->join('pbis','sprints.id','=','pbis.sprint_id')
        ->where('sprints.project_id', $project->id)
        ->where('pbis.eliminado', 0)
        ->orderByRaw('sprint_id ASC')
        ->get();

        $sprints = \DB::table('sprints')
        ->where('sprints.project_id', $project->id)
        ->get();

         return view('projects.show', compact('project','pbis','sprints'));
     }

     public function papelera_historias(Project $project)
     {

        $project = Project::find($project->id);
        
        $pbis = \DB::table('sprints')
       ->join('pbis','sprints.id','=','pbis.sprint_id')
       ->where('sprints.project_id', $project->id)
       ->where('pbis.eliminado', 1)
       ->orderByRaw('sprint_id ASC')
       ->get();

        
        $num_eliminados = count($pbis);
        return view('pbis.eliminados', compact('project','pbis','num_eliminados'));
    }

    public function papelera_tareas(Project $project)
    {

       $project = Project::find($project->id);
       
        $tareas = \DB::table('sprints')
        ->join('pbis','sprints.id','=','pbis.sprint_id')
        ->join('tareas','pbis.id','=','tareas.pbi_id')
        ->where('sprints.project_id', $project->id)
        ->where('tareas.eliminado', 1)
        ->orderByRaw('sprint_id ASC')
        ->get();
        //dd($tareas);
       $num_eliminados = count($tareas);
       return view('tareas.eliminados', compact('project','tareas','num_eliminados'));
   }
     /**
      * Show the form for editing the specified resource.
      *
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function edit(Project $project)
     {
         $project = Project::find($project->id);
         
         return view('projects.edit', ['project'=>$project]);
     }
 
     /**
      * Update the specified resource in storage.
      *
      * @param  \Illuminate\Http\Request  $request
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function update(Request $request, project $project)
     {
        $projectUpdate = Project::where('id', $project->id)
                            ->update([
                                'name'=> $request->input('name'),
                                'description'=> $request->input('description')
                            ]);
    
        if($projectUpdate){
            return redirect()->route('projects.show', ['project'=> $project->id])
            ->with('success' , 'Se actualizaron los datos del proyecto');
        }
        return back()->withInput();
     }
 
     /**
      * Remove the specified resource from storage.
      *
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function destroy(Project $project)
     {
         $findproject = Project::find( $project->id);
         if($findproject->delete()){
             return redirect()->route('projects.index')
             ->with('success' , 'Proyecto eliminado exitosamente');
         }
         return back()->withInput()->with('error' , 'No se pudo eliminar le proyecto');  
     }

     public function destroy_admin(Project $project)
     {
         $findproject = Project::find( $project->id);
         if($findproject->delete()){
             return redirect()->route('proyecto.todos')
             ->with('success' , 'Proyecto eliminado exitosamente');
         }
         return back()->withInput()->with('error' , 'No se pudo eliminar le proyecto');  
     }

     
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')




  <h1>Crear nuevo proyecto </h1>

  <div class="row">
      <div class="col-md-8">
       <!-- <div class="row justify-content-md-center">-->
      <form method="post" action="{{ route('projects.store') }}">
                            {{ csrf_field() }}


              <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                  <label for="project-name">Nombre<span class="required">*</span></label>
                  <input   placeholder="Nombre del proyecto"  
                            id="project-name"
                            required
                            name="nombre"
                            spellcheck="false"
                            class="form-control"
                            value="{{ old('nombre') }}"
                              />
                  @if ($errors->has('nombre'))
                    <span class="help-block">
                        <strong>{{ $errors->first('nombre') }}</strong>
                    </span>
                  @endif 
              </div>

              <div class="form-group">
                  <label for="project-content">Descripción</label>
                  <textarea placeholder="Descripción del proyecto" 
                            style="resize: vertical" 
                            id="project-content"
                            name="description"
                            rows="5" spellcheck="false"
                            class="form-control autosize-target text-left">{{old('description') }}                
                            </textarea>
              </div>
              <div class="form-group">
                  <input type="submit" class="btn btn-primary"
                          value="Crear"/>
              </div>
          </form>
      </div>



      <div class="col-md-4">
          <div class="tm-bg-primary-dark tm-block">
            <h4>Opciones</h4>
            <ol class="list-unstyled">
              <li><a href="/projects"><i class="fa fa-briefcase" 
                aria-hidden="true"></i> Mis proyectos</a></li>
            </ol>
          </div>
      </div>


    @endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')


<div class="row">
  <div class="col-md-8">
      <h1>Actualizar datos </h1>

      <!-- Example row of columns -->
        <form method="post" action="{{ route('projects.update',[$project->id]) }}">
                            {{ csrf_field() }}

                <input type="hidden" name="_method" value="put">

                <div class="form-group">
                    <label for="company-name">Nombre<span class="required">*</span></label>
                    <input   placeholder="Enter name"  
                              id="proyecto-name"
                              required
                              name="name"
                              spellcheck="false"
                              class="form-control"
                              value="{{ $project->name }}"
                                />
                </div>

                <div class="form-group">
                    <label for="company-content">Descripción</label>
                    <textarea class="form-control my-editor" placeholder="Datos adicionales del proyecto"
                    rows="4" id="nombre" name="description">{{  $project->description  }}</textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary"
                            value="Editar"/>
                </div>
        </form>
   </div>


        <div class="col-md-4">
            <div class="tm-bg-primary-dark tm-block ">
                  <div class="sidebar-module">
                    <h4>Opciones</h4>
                    <ol class="list-unstyled">
                      <li><a href="/projects/{{ $project->id }}"><i 
                        class="fa fa-undo" aria-hidden="true"></i> Backlog</a></li>

                      <li><a href="/projects"><i class="fa fa-building" 
                        aria-hidden="true"></i> Proyectos</a></li>
                      
                    </ol>
                  </div>
            </div>
        </div>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row tm-content-row">
    <h1 align=center> Proyectos </h1> 
    
    @if(count($projects) < 1 )
        <h2 align=center> No tiene proyectos, comience creando uno </h2>
    @endif
    <div class="col-md-4">
        <div class="panel panel-default ">
            <div class="panel-heading" > <p class="text-white">Mis Proyectos </p>
                <a  class="btn btn-primary btn-sm"  
                    href="/projects/create">
                    Crear </a> 
            </div>
            <div class="panel-body" >
                <ul class="list-group">
                    @foreach($projects as $project)
                        <li class="list-group-item"> 
                        <a href="/projects/{{ $project->id }}" > {{ $project->name }}</a>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    

    @if(count($proyectosInv)>0)
    <div class="col-md-4">
        <div class="panel panel-info ">
            <div class="panel-heading">  
                <p class="text-white">Invitado a </p> 
            </div>

            <div class="panel-body" >
                <ul class="list-group">
                    @foreach($proyectosInv as $proyectoInv)
                        <li class="list-group-item"> 
                            <a href="/projects/{{ $proyectoInv->id }}">{{ $proyectoInv->name }}</a>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    @endif
</div>

   

@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

  @section('content')


  <div class="row">
    <div class="col-12 tm-block-col">
          <div class="tm-bg-primary-dark tm-block ">
          <h1 align="center">{{ $project->name }}</h1>
          <p class="lead">{{ $project->description }}</p>
          </div>
    
    </div>

    <div class="col-md-8">
          <h1 align=center>PRODUCT BACKLOG</h1>
        
          <a href="{{ route('sprints.store', ['idproyecto' => $project->id]) }}" 
            class="pull-left btn btn-primary btn-sm">
            Crear sprint
          </a> 

          @if( count($sprints) > 0 ) 
            <a href="{{ route('pbis.create', ['idProyecto' => $project->id]) }}" 
              class="pull-right btn btn-primary btn-sm">
              Crear historia 
            </a>
          @else
            <h1>Primero debe crear sprints para registrar las historias de usuario</h1>
          @endif

      @if( count($pbis) > 0 ) 
      <table width="100" class="table table-striped table-hover table-reflow">
          <thead>
              <tr>
                  <th ><strong> HISTORIA </strong></th>
                  <th ><strong> SPRINT </strong></th>
                  <th ><strong> ESTIMACIÓN </strong></th>
                  <th ><strong> PRIORIDAD </strong></th>
              </tr>
          </thead>
          <tbody>
              @foreach($pbis as $pbi)
                  <tr>
                      <td> <a href="/pbis/edit/{{ $pbi->id }}" > {{ $pbi->titulo }}</a> </td>
                      {{-- <td> <a href="/pbis/{{ $pbi->id }}" > {{ $pbi->titulo }}</a> </td> --}}
                      <td> <a href="/sprints/{{ $pbi->sprint_id }}" > {{ $pbi->nombre }}</a></td>
                      <td>  {{ $pbi->estimacion }} </td>

                      <td>  
                          @if($pbi->prioridad_id == 3)
                              Baja
                                @elseif($pbi->prioridad_id == 2)
                                  Media
                                    @else
                                        Alta
                          @endif  
                      </td>
                      
                      
                  </tr> 
              @endforeach
          </tbody>
      </table>
      @endif
  </div>


      <div class="col-md-4">
        <div class="tm-bg-primary-dark tm-block">
            <div class="row justify-content-md-center">
              <div class="sidebar-module">
                <h4>Opciones</h4>
                <ol class="list-unstyled">

                  <li><a href="/projects/{{ $project->id }}/papelera/historias"><i class="fa fa-trash" 
                    aria-hidden="true"></i> Papelera de historias</a>
                  </li>

                  <li><a href="/projects/{{ $project->id }}/papelera/tareas"><i class="fa fa-trash" 
                    aria-hidden="true"></i> Papelera de tareas</a>
                  </li>

                  <li>
                    <a href="/projects/{{ $project->id }}/edit">
                    <i class="fa fa-edit" aria-hidden="true"></i> 
                    Editar</a>
                  </li>
    
                  <li> <a href="/proyecto/{{ $project->id }}/miembros"><i class="fa fa-users" 
                    aria-hidden="true"></i> Miembros</a>
                  </li>
    
                  <li><a href="/projects/create"><i class="fa fa-plus" 
                    aria-hidden="true"></i> Crear nuevo proyecto</a>
                  </li>
    
                  <li> <a href="/projects"><i class="fa fa-briefcase" 
                      aria-hidden="true"></i> Mis proyectos</a>
                  </li>
                <br/>
                
               

                @if($project->user_id == Auth::user()->id)
                  <li>
                  <i class="fa fa-power-off" aria-hidden="true"></i>
                  <a   
                  href="#"
                      onclick="
                      var result = confirm('Desea eliminar el proyecto?');
                          if( result ){
                                  event.preventDefault();
                                  document.getElementById('delete-form').submit();
                          }
                              "
                              >
                      Eliminar
                  </a>
    
                  <form id="delete-form" action="{{ route('projects.destroy',[$project->id]) }}" 
                    method="POST" style="display: none;">
                            <input type="hidden" name="_method" value="delete">
                            {{ csrf_field() }}
                  </form>
    
                  </li>
                @endif

              <h4>  <i class="fa fa-print" 
              aria-hidden="true"></i> Reportes</h4>
                <li>
                  <a href="{{ $project->id }}/reporte/sprints" > Reporte Sprints</a> 
                </li>
                <li>
                  <a href="{{ $project->id }}/reportes" > Reporte Historias</a> 
                </li>
                <li>
                    <a href="{{ $project->id }}/reporte/tareas" > Reporte Tareas</a> 
                </li>
                <li>
                    <a href="{{ $project->id }}/reporte/tareas_estado" > Reporte Estado de Tareas</a> 
                </li>
                <li>
                  <a href="{{ $project->id }}/reporte/equipo" > Reporte Equipo</a> 
                </li>

                </ol>
               <hr/>

          </div>
        </div>
      </div>
    </div>
@endsection

resources/views/projects/todos.blade.php
@extends('layouts.app')

@section('content')


<div class="row tm-content-row">
    <div class="col-md-12">
        <h1 align=center>
            {{ $num_proyects }} Proyecto(s) registrado(s) 
        </h1>
        @if($num_proyects>0)
        <table width="100" class="table table-striped table-hover table-reflow">
            <thead>
                <tr>
                    <th ><strong> ID </strong></th>
                    <th ><strong> Proyecto </strong></th>
                    <th ><strong> Descripción </strong></th>
                    <th ><strong> Eliminar </strong></th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach($proyectos as $proyecto)
                    <tr>
                        <td> {{$proyecto->id}}</td>
                        <td>
                            <a href="/projects/{{ $proyecto->id }}" > {{ $proyecto->name }}</a>
                        </td>
                        <td> {{$proyecto->description}}</td>
                        <td>
                            <a  
                                onclick="return confirm('Esta accion eliminara todo el proyecto')"
                                href="/admin/{{ $proyecto->id }}/eliminar" 
                                class="btn btn-danger btn-sm">
                                <i class="fa fa-times" aria-hidden="true"></i> 
                            </a> 
                        </td>
                        
                    </tr> 
                @endforeach
            </tbody>
        </table>
        @endif

        
    </div>
</div>

@endsection