routes/web.php
<?php
//header('Access-Control-Allow-Origin:  *');
//Route::get('/', 'TestimonialsController@home')->name('landing-page');
Route::get('/', function () {
    return view('welcome');
});


Route::get('/usuarios/activacion/{token}', 'Auth\RegisterController@activar');
//Route::get('/', 'loginController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::middleware(['auth'])->group(function () {

    Route::get('/pbi', 'PbisController@show')->name('pbi.show');
    Route::patch('/pbiEstado/{tarea}', 'PbisController@cambiarEst');
    Route::delete('/tarea/{tarea}', 'PbisController@destroyT');
    //Route::post('/tareas/create', 'TareasControlador@create')->name('tareas.create');
    Route::get('pbis/{pbi}/tareas/create', 'TareasControlador@create')->name('tareas.create');
    Route::post('/tareas/store', 'TareasControlador@store')->name('tareas.store');
    Route::get('/tareas/edit/{tarea}', 'TareasControlador@edit')->name('tareas.edit');
    Route::post('/tareas/update', 'TareasControlador@update')->name('tareas.update');

    Route::post('/tareas/subir', 'TareasControlador@subir')->name('tareas.subir');
    Route::get('/tareas/{tarea}/eliminar', 'TareasControlador@eliminar')->name('tarea.eliminar') ;
    Route::post('/tareas/delete', 'TareasControlador@borrar')->name('tarea.borrar');
    Route::get('/tareas/recuperar/{id}', 'TareasControlador@recuperar')->name('tarea.recuperar');
    Route::get('/tareas/{id}/historial', 'TareasControlador@historial')->name('tarea.historial');
    //Route::post('/tareas/delete/{id}', 'TareasControlador@borrar')->name('tarea.borrar');

    Route::get('/tareas/eliminararchivo/{id}', 'TareasControlador@deleteFile')->name('tarea.deletefile') ;

    
    Route::get('/proyecto/{project}/miembros', 'EquipoControlador@show')->name('miembros.show');
    Route::get('/miembros/eliminar/{projectuser}', 'EquipoControlador@destroy')->name('miembros.eliminar');
    Route::post('/miembros/anadir', 'EquipoControlador@anadir')->name('equipo.anadir');


    Route::get('/pbis/{pbi}/comentarios', 'ComentarioControlador@show')->name('coment.show');
    Route::post('/comentarios/crear', 'ComentarioControlador@store')->name('coment.store');
    Route::get('/comentario/{comentario}/eliminar', 'ComentarioControlador@destroy')->name('coment.elim');


    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::get('/projects/{project}/papelera/historias','ProjectsController@papelera_historias');
    Route::get('/projects/{project}/papelera/tareas','ProjectsController@papelera_tareas');
    
    Route::resource('companias', 'CompaniesController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('roles', 'RolesController');
    //Route::resource('tareas', 'TareasControlador');
    Route::resource('users', 'UsersController');
    //Route::resource('comments', 'CommentsController');
    Route::resource('pbis', 'PbisController');
    Route::resource('sprints', 'SprintsControlador');


    Route::get('/usuarios/{user}/editar', 'UsersController@edit')->name('usuarios.edit');
    Route::post('/usuarios/actualizar', 'UsersController@update')->name('usuarios.update');
    Route::get('/usuarios/{user}/eliminar', 'UsersController@destroy')->name('usuarios.delete');
    
    Route::get('/usuarios/{user}/activacion', 'UsersController@camEstado')->name('usuarios.cambiar');


    Route::get('pbis/edit/{id}', 'PbisController@edit')->name('pbis.edit');
    Route::get('pbis/update', 'PbisController@update')->name('pbis.update');
    Route::get('/pbis/delete/{id}', 'PbisController@eliminar')->name('pbis.eliminar');
    Route::post('/pbis/delete', 'PbisController@destroy')->name('pbis.delete');
    Route::get('/pbis/recuperar/{id}', 'PbisController@recuperar')->name('pbis.recuperar');
    Route::get('/pbis/{id}/historial', 'PbisController@historial')->name('pbis.historial');
    

    Route::get('sprints', 'SprintsControlador@store');
    Route::post('/sprints/create', 'SprintsControlador@create');
    Route::get('/sprints/delete/{id}', 'SprintsControlador@destroy')->name('sprints.delete');
    Route::get('sprints/edit/{id}', 'SprintsControlador@edit')->name('sprints.edit');
    Route::post('/sprints/update', 'SprintsControlador@update')->name('sprints.update');
    //Route::get('sprints/create', 'ProjectsController@createSprint');
    //Route::get('pbis/create', 'PbisController@store')->name('pbis.store');

    //administrador
    Route::get('/admin/proyectos', 'ProjectsController@todos')->name('proyecto.todos');
    Route::get('/admin/{project}/eliminar', 'ProjectsController@destroy_admin')->name('proyecto.delete');
    //reportes
    Route::get('projects/{project}/reporte/sprints', 'ReportesControlador@rep_sprints');
    Route::get('projects/{project}/reportes', 'ReportesControlador@rep_pro_bac');
    Route::get('projects/{project}/reporte/tareas', 'ReportesControlador@rep_tar');
    Route::get('projects/{project}/reporte/tareas_estado', 'ReportesControlador@rep_tar_est');
    Route::get('projects/{project}/reporte/equipo', 'ReportesControlador@rep_usuarios');

    
});

app/Sprint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sprint extends Model
{
    protected $fillable = [
        'id',
        'nombre',
        'descripcion',
        'project_id'

    ];

    public function project(){
        return $this->belongsTo('App\Project');
    }

    public function pbis()
    {
    	return $this->hasMany('App\Pbi');
    }
}

resources/views/sprints/create.blade.php
@extends('layouts.app')

@section('content')

     
<div class="col-md-8">
    <h1>Crear Sprint </h1>
      <form method="post" action="{{ route('sprints.create') }}">
                            {{ csrf_field() }}

          <input   
          class="form-control"
          type="hidden"
                  name="idproject"
                  dd($id_proyec);
                  value="{{ $id_proyec }}"
                    />
          
        
        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
              <label for="company-name">Nombre<span class="required">*</span></label>
              <input    placeholder="Nombre del sprint"  
                        id="company-name"
                        required
                        name="nombre"
                        spellcheck="false"
                        class="form-control"
                        value="{{ old('nombre') }}"
                          />
                @if ($errors->has('nombre'))
                    <span class="help-block">
                        <strong>{{ $errors->first('nombre') }}</strong>
                    </span>
                @endif 
        </div>


          <div class="form-group">
              <label for="company-content">Descripción</label>
              <textarea class="form-control" placeholder="Descripcion del sprint"
              rows="4" id="nombre" name="description">{{ old('description') }}</textarea>
          </div>

        {{--}}
        <div class="form-group">
            <label>Select Due Date <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></label>
            <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" id ="datepicker1"name="duedate">
                <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <input id="datepicker0" class="form-control" width="276" value="Fecha inicio" name="fecha_inicio"/>
        --}}
          <div class="form-group">
              <input type="submit" class="btn btn-primary"
                      value="Crear"/>
          </div>
          
      </form>
  </div>
@endsection
   

@section('scripts')
    <script src="{{ asset('js/moment.js') }}"></script> 
    <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    
    <script>
              $('#datepicker0').datetimepicker( {
                    //format: 'YYYY-MM-DD',  // YEAR-MONTH-DAY hour:minute:seconds
                });
                /*$('#datetimepicker1').datetimepicker( {
                    defaultDate:'now',  // defaults to today
                    format: 'YYYY-MM-DD hh:mm:ss',  // YEAR-MONTH-DAY hour:minute:seconds
                    minDate:new Date()  // Disable previous dates, minimum is todays date
                });*/
    </script>
@stop

resources/views/sprints/edit.blade.php
@extends('layouts.app')

@section('content')



<div class="row">
    <div class="col-md-8">
      <h1>Actualizar datos del sprint  {{ $sprint->nombre }} </h1>

      <!-- Example row of columns -->
      

                                 
      <form method="post" action="{{ route('sprints.update') }}">
                            {{ csrf_field() }}

              <input type="hidden" name="sprint_id" value="{{ $sprint->id }}">
              {{-- <input type="hidden" name="sprint_id" value="{{ $project->id }}"> --}}
              <input type="hidden" name="_method" value="put">


              <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                  <label for="company-name">Nombre<span class="required"></span></label>
                  <input   placeholder="Enter name"  
                            id="proyecto-name"
                            required
                            name="nombre"
                            spellcheck="false"
                            class="form-control"
                            value="{{ $sprint->nombre }}"
                              />
                  @if ($errors->has('nombre'))
                    <span class="help-block">
                        <strong>{{ $errors->first('nombre') }}</strong>
                    </span>
                  @endif 
              </div>

              <div class="form-group">
                <label for="company-content">Descripción</label>
                <textarea class="form-control my-editor" placeholder="Información acerca del sprint"
                rows="4" id="nombre" name="description">{{  $sprint->descripcion  }}</textarea>
              </div>

              <div class="form-group">
                  <input type="submit" class="btn btn-primary"
                          value="Submit"/>
              </div>
          </form>
   
      </div>



    <div class="col-md-4">
        <div class="tm-bg-primary-dark tm-block">
            <h4>Opciones</h4>
            <ol class="list-unstyled">
              <li><a href="/projects/{{ $proyecto_id }}"><i class="fa fa-undo" 
                aria-hidden="true"></i> Product backlog</a></li>
              <li><a href="/projects"><i class="fa fa-building" 
                aria-hidden="true"></i> Proyectos</a></li>
            </ol>
        </div>
    </div>
  </div>

@endsection

resources/views/sprints/show.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-8">
        <h3>Historias del sprint <b>  </b></h3>

        <table width="100" class="table table-striped table-hover table-reflow">
                <thead>
                    <tr>
                        <th ><strong> HISTORIA </strong></th>
                        <th ><strong> OPCIONES </strong></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($pbis as $pbi)
                        <tr>
                            <td> <a href="/pbis/{{ $pbi->id }}" > {{ $pbi->titulo }}</a>  </td>
                            <td> 
                                <a  href="/pbis/edit/{{ $pbi->id }}" 
                                    class="btn btn-primary btn-sm">
                                    <i class="fa fa-edit" aria-hidden="true"></i> 
                                </a>  
                                
                                <a  onclick="return confirm('¿Desea eliminar la historia?')"
                                    href="/pbis/delete/{{ $pbi->id }}" 
                                    class="btn btn-danger btn-sm">
                                    <i class="fa fa-times" aria-hidden="true"></i> 
                                </a>   
                            </td>
                        </tr> 
                    @endforeach
                </tbody>
        </table>   
    </div>

    <div class="col-md-4">
        <div class="tm-bg-primary-dark tm-block">
            <h1>{{ $sprint->nombre }}</h1>
            <p class="lead">{{ $sprint->descripcion }}</p>
        
            <div>
                <a href="{{ route('sprints.edit', ['id' => $sprint->id ]) }}">
                <i class="fa fa-edit" aria-hidden="true"></i> Editar</a>
            </div>
            
            <div>
                <a  onclick="return confirm('¿Quiere eliminar el sprint?')" 
                href="{{ route('sprints.delete', ['id' => $sprint->id]) }}" >
                <i class="fa fa-power-off" aria-hidden="true"></i> Eliminar</a>
            </div>
            
        </div>
    </div>

</div>
@endsection