routes/web.php
<?php
//header('Access-Control-Allow-Origin:  *');
//Route::get('/', 'TestimonialsController@home')->name('landing-page');
Route::get('/', function () {
    return view('welcome');
});


Route::get('/usuarios/activacion/{token}', 'Auth\RegisterController@activar');
//Route::get('/', 'loginController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::middleware(['auth'])->group(function () {

    Route::get('/pbi', 'PbisController@show')->name('pbi.show');
    Route::patch('/pbiEstado/{tarea}', 'PbisController@cambiarEst');
    Route::delete('/tarea/{tarea}', 'PbisController@destroyT');
    //Route::post('/tareas/create', 'TareasControlador@create')->name('tareas.create');
    Route::get('pbis/{pbi}/tareas/create', 'TareasControlador@create')->name('tareas.create');
    Route::post('/tareas/store', 'TareasControlador@store')->name('tareas.store');
    Route::get('/tareas/edit/{tarea}', 'TareasControlador@edit')->name('tareas.edit');
    Route::post('/tareas/update', 'TareasControlador@update')->name('tareas.update');

    Route::post('/tareas/subir', 'TareasControlador@subir')->name('tareas.subir');
    Route::get('/tareas/{tarea}/eliminar', 'TareasControlador@eliminar')->name('tarea.eliminar') ;
    Route::post('/tareas/delete', 'TareasControlador@borrar')->name('tarea.borrar');
    Route::get('/tareas/recuperar/{id}', 'TareasControlador@recuperar')->name('tarea.recuperar');
    Route::get('/tareas/{id}/historial', 'TareasControlador@historial')->name('tarea.historial');
    //Route::post('/tareas/delete/{id}', 'TareasControlador@borrar')->name('tarea.borrar');

    Route::get('/tareas/eliminararchivo/{id}', 'TareasControlador@deleteFile')->name('tarea.deletefile') ;

    
    Route::get('/proyecto/{project}/miembros', 'EquipoControlador@show')->name('miembros.show');
    Route::get('/miembros/eliminar/{projectuser}', 'EquipoControlador@destroy')->name('miembros.eliminar');
    Route::post('/miembros/anadir', 'EquipoControlador@anadir')->name('equipo.anadir');


    Route::get('/pbis/{pbi}/comentarios', 'ComentarioControlador@show')->name('coment.show');
    Route::post('/comentarios/crear', 'ComentarioControlador@store')->name('coment.store');
    Route::get('/comentario/{comentario}/eliminar', 'ComentarioControlador@destroy')->name('coment.elim');


    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::get('/projects/{project}/papelera/historias','ProjectsController@papelera_historias');
    Route::get('/projects/{project}/papelera/tareas','ProjectsController@papelera_tareas');
    
    Route::resource('companias', 'CompaniesController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('roles', 'RolesController');
    //Route::resource('tareas', 'TareasControlador');
    Route::resource('users', 'UsersController');
    //Route::resource('comments', 'CommentsController');
    Route::resource('pbis', 'PbisController');
    Route::resource('sprints', 'SprintsControlador');


    Route::get('/usuarios/{user}/editar', 'UsersController@edit')->name('usuarios.edit');
    Route::post('/usuarios/actualizar', 'UsersController@update')->name('usuarios.update');
    Route::get('/usuarios/{user}/eliminar', 'UsersController@destroy')->name('usuarios.delete');
    
    Route::get('/usuarios/{user}/activacion', 'UsersController@camEstado')->name('usuarios.cambiar');


    Route::get('pbis/edit/{id}', 'PbisController@edit')->name('pbis.edit');
    Route::get('pbis/update', 'PbisController@update')->name('pbis.update');
    Route::get('/pbis/delete/{id}', 'PbisController@eliminar')->name('pbis.eliminar');
    Route::post('/pbis/delete', 'PbisController@destroy')->name('pbis.delete');
    Route::get('/pbis/recuperar/{id}', 'PbisController@recuperar')->name('pbis.recuperar');
    Route::get('/pbis/{id}/historial', 'PbisController@historial')->name('pbis.historial');
    

    Route::get('sprints', 'SprintsControlador@store');
    Route::post('/sprints/create', 'SprintsControlador@create');
    Route::get('/sprints/delete/{id}', 'SprintsControlador@destroy')->name('sprints.delete');
    Route::get('sprints/edit/{id}', 'SprintsControlador@edit')->name('sprints.edit');
    Route::post('/sprints/update', 'SprintsControlador@update')->name('sprints.update');
    //Route::get('sprints/create', 'ProjectsController@createSprint');
    //Route::get('pbis/create', 'PbisController@store')->name('pbis.store');

    //administrador
    Route::get('/admin/proyectos', 'ProjectsController@todos')->name('proyecto.todos');
    Route::get('/admin/{project}/eliminar', 'ProjectsController@destroy_admin')->name('proyecto.delete');
    //reportes
    Route::get('projects/{project}/reporte/sprints', 'ReportesControlador@rep_sprints');
    Route::get('projects/{project}/reportes', 'ReportesControlador@rep_pro_bac');
    Route::get('projects/{project}/reporte/tareas', 'ReportesControlador@rep_tar');
    Route::get('projects/{project}/reporte/tareas_estado', 'ReportesControlador@rep_tar_est');
    Route::get('projects/{project}/reporte/equipo', 'ReportesControlador@rep_usuarios');

    
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Improve') }}</title>


   
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>




    <link rel="stylesheet" href="{{ asset ('font-awesome-5/css/fontawesome-all.min.css')}}">
    <!-- https://fontawesome.com/ -->
{{--    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
    --}}


    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="{{asset ('css/templatemo-style.css')}}">
    <style>

        #celda {
        color:white;
        text-align:center;
        }
    </style>

</head>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Gesti</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            {{--<li class="nav-item">
                <a class="nav-link" href="{{ url('/home') }}">
                <i class="fa fa-home" aria-hidden="true"></i>Home</a>
            </li>--}}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            @guest
                <li class="nav-item">
                    <a  class="nav-link" href="{{ route('login') }}">
                    <i class="fa fa-sign-in-alt" aria-hidden="true"></i> Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">
                    <i class="fa fa-user-plus" aria-hidden="true"></i> Registro</a>
                </li>
            @else
                @if(Auth::user()->role_id == 1) 
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/proyectos">
                        <i class="fa fa-briefcase" aria-hidden="true"></i> Todos los Proyectos</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('users.index') }}">
                        <i class="fa fa-user" aria-hidden="true"></i> Todos los Usuarios</a>
                    </li>
                @endif  
                
            <li class="nav-item">
                    <a class="nav-link" href="{{ url('/home') }}">
                    <i class="fa fa-home" aria-hidden="true"></i>Home</a>
                </li>
            <li class="nav-item">
                    <a class="nav-link" href="{{ route('projects.index') }}">
                    <i class="fa fa-briefcase" aria-hidden="true"></i> Proyectos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/usuarios/{{ Auth::user()->id }}/editar">
                <i class="fa fa-user" aria-hidden="true"></i> Perfil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    <i class="fa fa-power-off" aria-hidden="true"></i> Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" 
                    method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>        
            </li>
            @endif
        </ul>
      </div>
    </div>
  </nav> 
 


<body>
    
    <div id="app">
        
      

        <div class="container" >
            @include('partials.errors')
            @include('partials.success')
            @yield('content')
        </div>

    </div>

    <footer class="tm-footer row tm-mt-small">
        <div class="col-12 font-weight-light">
            <p class="text-center text-white mb-0 px-4 small"> 
             Copyright © PROYECTO DE GRADO <b>II-2019</b>
            </p>
        </div>
    </footer>

    <script src="{{ asset('js/app.js') }}"></script>

    @yield('jqueryScript')
</body>
</html>